name: farm-infra-apply
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  apply:
    name: Apply Terraform Updates
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_bucket: ${{ secrets.TF_VAR_BUCKET }}
      TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
      TF_VAR_key: ${{ secrets.TF_VAR_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6

      - name: Initialize Terraform
        run: terraform init
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Plan Terraform
        run: terraform plan
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Apply Terraform
        run: terraform apply -auto-approve
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
